### ISSUE TITLE
Change Image Files Names to Lower Case with Hyphens

### ISSUE THREAD

**Issue by thecodeclimber** [thecodeclimber/ramsay-site#1]
@kirti75waytech Please watch the following video and make the appropriate changes.  Thanks.

https://www.loom.com/share/90445b0eb043453bb7014f7694cadd86

**Comment by kirti75waytech** [comment]
Sure i will change that tomorrow morning.

**Comment by kirti75waytech** [comment]
This is done yesterday, please verify and let me know if any other change required.

**Comment by thecodeclimber** [comment]
Thanks :)
