### ISSUE TITLE
Update Footer Content

### ISSUE THREAD

**Issue by thecodeclimber** [thecodeclimber/ramsay-site#11]
Please update the following in the footer:

# CONTACT DETAILS

![image](https://user-images.githubusercontent.com/65869221/100140858-34c37c80-2e9a-11eb-95f8-a9420f497aab.png)

Please change to the following:

* info@ramsayinnovations.com
* (312) 872-7202

# LEARN MORE 

![image](https://user-images.githubusercontent.com/65869221/100140563-ca124100-2e99-11eb-8393-60eca97cbb71.png)

## Text

Please change the following:

* The Ramsay Way --. The Ramsay Method
* The Ramsay Coach --> The Ramsay Advisor
* The Ramsay Structure --> The Ramsay Commitment

## Links

Please have these links scroll up to the relevant sections above.

# LINKS SECTION

![image](https://user-images.githubusercontent.com/65869221/100141633-68eb6d00-2e9b-11eb-8529-908013e497de.png)

## Text

Please change the following text:

* Terms of Service --> Terms and Conditions
* Privacy Policity --> Privacy Policy
* About Us --> Cookies Policy

Please use the following URLs for each link

* Terms and Conditions:  https://www.termsfeed.com/live/052cf669-4b0d-4d3b-aea4-388ded2de1f8
* Privacy Policy: https://www.termsfeed.com/live/54160450-d627-4713-b38b-729c3a56295b
* Cookies Policy: https://www.termsfeed.com/live/172ec218-b2c1-43e4-ad23-7ac3c63e6653

# SOCIAL ICONS

![image](https://user-images.githubusercontent.com/65869221/100142903-304c9300-2e9d-11eb-91e8-3cc418e44f28.png)

Please add the following link:

* LinkedIn: https://www.linkedin.com/company/ramsay-innovations-llc
* Facebook: https://www.facebook.com/RamsayInnovations/ 
* Twitter:  https://twitter.com/RamsayInno
* Youtube: https://www.youtube.com/channel/UCFs3tDqN3AA8tKM2PN1Lxmg

# COPYRIGHT 

![image](https://user-images.githubusercontent.com/65869221/100140788-1a899e80-2e9a-11eb-8abc-56faaaa5033c.png)

Please create a script that automatically updates the copyright year to the appropriate year.

**Comment by kirti75waytech** [comment]
@thecodeclimber Completed and deployed. Please verify and let me know if you need any other change. Thanks

**Comment by thecodeclimber** [comment]
Thanks -- almost done.

First of all, I made a slight textual change:

* The Ramsay Method --> Ramsay Method
* The Ramsay Advisor  --> Ramsay Advisor
* The Ramsay Commitment  --> Ramsay Commitment

---

Secondly, we need to add links:

* Ramsay Method:  Link to The Ramsay Method
* Ramsay Advisor:  Link to The Ramsay Advisor
* Ramsay Commitment:  Link to The Ramsay Commitment

See video:  https://www.loom.com/share/9bda6b4653f34f18a8458d8058bbccac

**Comment by kirti75waytech** [comment]
Fixed. Thanks
