### ISSUE TITLE
Update Font Sizes and Styles to Match Figma File

### ISSUE THREAD

**Issue by thecodeclimber** [thecodeclimber/ramsay-site#13]
Please fix up all of the font sizes and styles to match the figma file.

Here is a video explanation:  https://www.loom.com/share/ab40f24e696b4f3fb7b899d9cc38ab58

**Comment by kirti75waytech** [comment]
@thecodeclimber I have updated all the fonts as per the latest design on figma and tried to use the exact font or the closest font size in case the exact font doesn't found. This is done for both web, tablet and mobile resolution. I have pushed my code to main branch. Please test it and let me know in case you want any other changes.
Thanks

**Comment by kirti75waytech** [comment]
@thecodeclimber Completed and deployed. Please verify and let me know if you need any other change. Thanks
