### ISSUE TITLE
Move Home Folder Out of Layouts

### ISSUE THREAD

**Issue by thecodeclimber** [thecodeclimber/ramsay-site#14]
Please see video instructions:  https://www.loom.com/share/9c6f7c28ce7b481e90d4152d039947e1

# Tasks to do

* Inside of the `components ` folder, create a new folder called `pages`
* Move the `home` folder inside of `components/layouts/main` into the `pages` folder
* Remove `home` component from `components/layouts/main/index.js`
* Add `home` component to `pages/index.js`

Please let me know if you have any questions.

**Comment by kirti75waytech** [comment]
@thecodeclimber Completed and deployed. Please verify and let me know if you need any other change. Thanks

**Comment by thecodeclimber** [comment]
Thanks.
