### ISSUE TITLE
Remove Text Underneath Contact Us Form

### ISSUE THREAD

**Issue by thecodeclimber** [thecodeclimber/ramsay-site#17]
Please remove the following from below the contact form:

![image](https://user-images.githubusercontent.com/65869221/100272203-62282d00-2f63-11eb-8ec6-c6121d00e9bf.png)

**Comment by kirti75waytech** [comment]
@thecodeclimber Completed and deployed. Please verify and let me know if you need any other change. Thanks

**Comment by thecodeclimber** [comment]
Thanks.
