### ISSUE TITLE
Replace Bio and Testimonial Photos

### ISSUE THREAD

**Issue by thecodeclimber** [thecodeclimber/ramsay-site#19]
Please take note of the following video:  https://www.loom.com/share/c7ec847198f74280beef5e84e960dd5a

To summarize:

* Change the bio photo on the site with the bio photo in figma
* Change the testimonial photos on the site with the testimonial photos in figma
  - Keep the same order of the photos as it appears in figma.

Thanks.

**Comment by thecodeclimber** [comment]
Can I close this issue?  It looks like you did it :)

**Comment by kirti75waytech** [comment]
Yes this is done, please close it. Thanks
