### ISSUE TITLE
Rename Compontents/pages to Components/content

### ISSUE THREAD

**Issue by thecodeclimber** [thecodeclimber/ramsay-site#20]
Hello, please take a look at this video:  https://www.loom.com/share/2bf021cdfe8a4f928621c86fbcfca6b2

# Tasks

* Rename the `components/pages` folder to `components/content`
* Update the import statement in `pages/index.js`:
  - Change from `import Home from "@/components/page/home"` to `import Home from "@/components/content/home"`

**Comment by kirti75waytech** [comment]
This one is also completed. Please review and let me know in case of any other changes are required. Thanks
