### ISSUE TITLE
Footer Links in Tablet & Mobile View

### ISSUE THREAD

**Issue by thecodeclimber** [thecodeclimber/ramsay-site#21]
Please watch the following video:  https://www.loom.com/share/ab90d46d19b941b6a18c1aa75a33d49b

# Tasks

* Keep 'Links' on left and 'Learn More' on right in Tablet View
* 'Cookie Policy' link should be in the 'Links' section in Mobile view

**Comment by kirti75waytech** [comment]
This one is also completed. Please review and let me know in case of any other changes are required. Thanks
