### ISSUE TITLE
Footer Email & Phone Link

### ISSUE THREAD

**Issue by thecodeclimber** [thecodeclimber/ramsay-site#25]
I am referring to this section:

![image](https://user-images.githubusercontent.com/65869221/100655226-acd6ea00-3353-11eb-9c99-bd8a00e313a9.png)

# Tasks

* Email link should be clickable to send an email
* Phone link should be clickable to make a phone call

**Comment by kirti75waytech** [comment]
This one is also completed. Please review and let me know in case of any other changes are required. Thanks
