### ISSUE TITLE
Fix background of The Ramsay Way section

### ISSUE THREAD

**Issue by thecodeclimber** [thecodeclimber/ramsay-site#4]
https://www.loom.com/share/2abbf099799543fa91088e7c2c7cac83

**Comment by kirti75waytech** [comment]
This is done today, please verify and let me know if any other change required.

**Comment by thecodeclimber** [comment]
I don't see the background lines in this section.  Here is a screen shot:

![image](https://user-images.githubusercontent.com/65869221/100001465-e182f880-2dcb-11eb-8c02-f5be26f728ca.png)
