### ISSUE TITLE
Add Testimonial Blurb to Testimonial Section

### ISSUE THREAD

**Issue by thecodeclimber** [thecodeclimber/ramsay-site#6]
Please add the following text as the blurb in the testimonial sectdion:

> Leading business luminaries and existing clients  understand the benefit of working with Ramsay Innovations

![image](https://user-images.githubusercontent.com/65869221/100006945-f2376c80-2dd3-11eb-9152-573e17ee9f8d.png)

**Comment by kirti75waytech** [comment]
@thecodeclimber Completed and deployed. Please verify and let me know if you need any other change. Thanks

**Comment by thecodeclimber** [comment]
Great, thanks.
